package kmptmp.composeapp.RoomDB

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

//Database layer that points to everything
//Entities in annotation, DAO in class

@Database(
    version = 1, entities = [NoteEntity::class],
    //TODO exportSchema?
)
@ConstructedBy(DbConstructor::class)
abstract class RemindFulDB : RoomDatabase() {
    //Declare DAOs else cannot ref and find
    abstract fun NotesDao() : NotesDAOs
}
    //generated by room -- ignore
@Suppress("KotlinNoActualForExpect")
expect object DbConstructor : RoomDatabaseConstructor<RemindFulDB>{
    override fun initialize(): RemindFulDB
}